from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from .secret_vault import SecretVaultError, get_secret, vault_enabled


_LAST_FLUSH_AT = 0.0


def _enabled() -> bool:
    raw = (os.getenv("XBOW_ENABLE_REPO_LEARNING_PUSH") or "false").strip().lower()
    if raw in {"1", "true", "yes", "on"}:
        return True
    if raw in {"0", "false", "no", "off", ""}:
        return False
    return False


def _outbox_root() -> Path:
    return Path(os.getenv("XBOW_REPO_LEARNING_OUTBOX", "/data/repo-learning-outbox"))


def _token() -> str | None:
    try:
        use_vault = vault_enabled()
    except SecretVaultError:
        return None
    if use_vault:
        try:
            value = get_secret("github_learning_token")
        except SecretVaultError:
            return None
        return value.strip() or None
    value = (os.getenv("XBOW_GITHUB_LEARNING_TOKEN") or "").strip()
    return value or None


def _repo() -> str:
    value = (os.getenv("XBOW_GITHUB_LEARNING_REPO") or "dbrckk/xbow-perso").strip()
    if value.count("/") != 1 or any(ch.isspace() for ch in value):
        return "dbrckk/xbow-perso"
    return value


def _record_path(batch_id: str) -> Path:
    safe = "".join(ch for ch in batch_id if ch.isalnum() or ch in "-_")[:128]
    if not safe:
        safe = "unknown"
    return _outbox_root() / f"{safe}.json"


def persist_learning_brief(brief: dict[str, Any]) -> dict[str, Any]:
    batch_id = str(brief.get("batch_id") or "")
    root = _outbox_root()
    root.mkdir(parents=True, exist_ok=True)
    os.chmod(root, 0o700)
    path = _record_path(batch_id)
    if path.exists():
        try:
            existing = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            existing = {}
        return {
            "queued": True,
            "delivered": bool(existing.get("delivered")),
            "issue_url": existing.get("issue_url"),
            "reason": existing.get("reason"),
        }

    payload = {
        "schema_version": 1,
        "batch_id": batch_id,
        "brief": brief,
        "delivered": False,
        "issue_url": None,
        "reason": "github_delivery_disabled" if not _enabled() else "pending",
        "created_at": brief.get("updated_at") or brief.get("created_at"),
    }
    tmp = path.with_suffix(".tmp")
    tmp.write_text(
        json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")),
        encoding="utf-8",
    )
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)
    os.chmod(path, 0o600)
    return {
        "queued": True,
        "delivered": False,
        "issue_url": None,
        "reason": payload["reason"],
    }


def learning_delivery_status(batch_id: str) -> dict[str, Any]:
    path = _record_path(batch_id)
    if not path.exists():
        return {
            "queued": False,
            "delivered": False,
            "issue_url": None,
            "reason": "not_queued",
        }
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {
            "queued": True,
            "delivered": False,
            "issue_url": None,
            "reason": "outbox_record_invalid",
        }
    return {
        "queued": True,
        "delivered": bool(payload.get("delivered")),
        "issue_url": payload.get("issue_url"),
        "reason": payload.get("reason"),
    }


def _issue_body(brief: dict[str, Any]) -> str:
    encoded = json.dumps(brief, ensure_ascii=False, indent=2, sort_keys=True)
    if len(encoded) > 52000:
        encoded = encoded[:52000] + "\n...TRUNCATED..."
    return (
        "Runtime learning summary generated by xbow-perso.\n\n"
        "This is sanitized operational learning data only; it contains no API tokens, "
        "raw job payloads or authorization expansion. It must not auto-merge code.\n\n"
        "~~~json\n" + encoded + "\n~~~"
    )


def _deliver_record(path: Path, payload: dict[str, Any]) -> bool:
    token = _token()
    if not token:
        payload["reason"] = "github_learning_token_missing"
        path.write_text(
            json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")),
            encoding="utf-8",
        )
        os.chmod(path, 0o600)
        return False

    brief = dict(payload.get("brief") or {})
    batch_id = str(payload.get("batch_id") or brief.get("batch_id") or "")
    data = json.dumps(
        {
            "title": f"[runtime-learning] batch {batch_id}",
            "body": _issue_body(brief),
        }
    ).encode("utf-8")
    request = urllib.request.Request(
        f"https://api.github.com/repos/{_repo()}/issues",
        data=data,
        method="POST",
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": "xbow-perso-runtime-learning",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            document = json.loads(response.read(1_000_000).decode("utf-8"))
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, json.JSONDecodeError):
        payload["reason"] = "github_delivery_failed"
        path.write_text(
            json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")),
            encoding="utf-8",
        )
        os.chmod(path, 0o600)
        return False

    payload["delivered"] = True
    payload["issue_url"] = str(document.get("html_url") or "")
    payload["reason"] = "delivered"
    path.write_text(
        json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")),
        encoding="utf-8",
    )
    os.chmod(path, 0o600)
    return True


def maybe_flush_learning_outbox(*, interval_seconds: int = 60, max_items: int = 3) -> int:
    global _LAST_FLUSH_AT
    if not _enabled():
        return 0
    now = time.monotonic()
    if now - _LAST_FLUSH_AT < max(10, interval_seconds):
        return 0
    _LAST_FLUSH_AT = now

    root = _outbox_root()
    if not root.exists():
        return 0
    delivered = 0
    for path in sorted(root.glob("*.json"))[: max(1, min(max_items, 10))]:
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        if payload.get("delivered") is True:
            continue
        if _deliver_record(path, payload):
            delivered += 1
    return delivered
